// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH0NdmJBOoKulnzLTx-mPIzuIZk33MgYM',
    appId: '1:149250338687:web:03cc9ccaa1c5d5c25ff44a',
    messagingSenderId: '149250338687',
    projectId: 'bancomovimentacao',
    authDomain: 'bancomovimentacao.firebaseapp.com',
    storageBucket: 'bancomovimentacao.appspot.com',
    measurementId: 'G-XG8FRS592K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7MUrHPAakS6lfXJiObYJ0GsCh_0RPjYs',
    appId: '1:149250338687:android:55a2df35abc3f7925ff44a',
    messagingSenderId: '149250338687',
    projectId: 'bancomovimentacao',
    storageBucket: 'bancomovimentacao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYc_YDHNI50L68M7oFa1fYjfaU-uYALc0',
    appId: '1:149250338687:ios:a5f4c1c7cc6b43c95ff44a',
    messagingSenderId: '149250338687',
    projectId: 'bancomovimentacao',
    storageBucket: 'bancomovimentacao.appspot.com',
    iosBundleId: 'com.example.projeto',
  );
}
